add tiramisu to archive
Lazr1026/Guide-WiiU pull request #1
Opened 2023-11-17 17:58 UTC by SirGamers

2023-11-18 00:06 UTC, Lazr1026 commented
could you put Tiramisu under the cfw-choice? i dont see why it needs to be on the sidebar

2023-11-18 00:42 UTC, SirGamers commented
it doesnt belong there cuz the cfw choice is for stuff not supported anymore

2023-11-18 00:44 UTC, SirGamers commented
but tiramisu is still supported

2023-11-20 20:32 UTC, SirGamers commented
[test site here](https://sirgamers.github.io/Guide-WiiU/)

2023-11-20 20:54 UTC, SirGamers commented
i love how you can undo stuff using git

2023-11-22 15:50 UTC, SirGamers commented
@Lazr1026 merge???

2023-11-22 16:02 UTC, Lazr1026 commented on index.html
> +                '/archive/tiramisu/sd-preparation'                    : '/docs/user-guide/archive/tiramisu/sd-preparation.md',
is there a need for this twice? (see line 80)

2023-11-22 21:34 UTC, SirGamers commented
fixed

2023-11-27 05:24 UTC, Lazr1026 requested changes

2023-11-27 05:24 UTC, Lazr1026 commented on docs/user-guide/archive/tiramisu/finalizing-setup.md
> +### Installing Aroma
Can probably just remove this section entirely

2023-11-27 05:24 UTC, Lazr1026 commented
sorry for late review, i was on vacation for thanksgiving

2023-11-27 21:06 UTC, SirGamers commented
> sorry for late review, i was on vacation for thanksgiving

It’s fine

2023-12-07 16:14 UTC, SirGamers commented
i removed it

2023-12-10 20:42 UTC, merged